language: none

branches:
  only:
    - master

env:
  global:
    - SOD_VERSION="3.2.9"
    - PATH="${PATH}:${HOME}/sod-${SOD_VERSION}/bin"

install:
  - wget http://www.seis.sc.edu/downloads/sod/${SOD_VERSION}/sod-${SOD_VERSION}.tgz -O - | tar -xz -C ${HOME}
  - sod --version

script:
  - cd .ci;
    python makeRecipes.py;
    for recipe in $(ls *.xml); do
        echo $recipe;
        sod -V -f $recipe;
    done
